### ISSUE TITLE
도메인 구입?

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/FdAS#13]
뭘로 할까요?
- [ ] fdas.kr ?
- [ ] findingsofaddleseoul.kr ?
- [x] alddleseoul.kr ?
- [ ] fdas.codeforseoul.kr

**Comment by kkh975** [comment]
이미 이전에 논의가 있었군여...
다시 한번 논의를 불태울께여~
어제 이야기한거 다시 정리해서 올려요

- [] 뭐 이런걸다.com
- [] 개이득.com
- [] 개정승.com
- [] 엉망진창.com
- [] nogoas.com
- [] benefit4u.com
- [] welfare4u.com
- [] civic4u.com
- [] citypicker.com
- [] citypick.com
- [] ().codeforseoul.org | 코드포서울 하위에 위치

**Comment by kkh975** [comment]
뭐 이런걸다.com
개이득.com
개정승.com
엉망진창.com
nogoas.com
benefit4u.com
welfare4u.com
civic4u.com
citypicker.com
citypick.com
___.codeforseoul.org | 코드포서울 하위에 위치

**Comment by Yeyeon** [comment]
나에게 맞는 복지서비스라는 의미를 가장 잘 전달한다는 면에서
welfare4u.com

citypicker.com 도 괜찮은거 같아요!


..저 위에 한글도메인은 어쩌다가...ㅎㅎ 뒤에 남았어야 하는건데!

**Comment by EthanJonghoonLee** [comment]
welfare4u.com 
무미건조해 보일수는 있지만 그래도 가장 심플하게 이게 뭐다라고 이해할 수 있는 단어이기에..

쁠라스알파로 개이득.com

**Comment by mozodev** [comment]
어젯밤 알콜 기운이 느껴지는 도메인들이 많이 보여서 재밌네요 ㅎㅎㅎ

아 가장 간단한게 프로젝트명과 코드포서울 도메인을 사용하는거군요..
도메인 살 필요도 없고....

맨 정신에 보니
fdas.codeforseoul.org
이거 사용하면 되겠네요. fdas가 어색하면 이걸 뭔가로 바꾸는 것도 좋겠어요.
재미는 없네요 확실히~ ㅋㅋㅋ

**Comment by thechunsik** [comment]
저는 코드포서울 도메인과 분리하는 것에 한표! 근데 뭔가 알콜냄새나는 도메인들..ㅋㅋㅋ이 많아서 welfare4u.kr에 한표 던지고 싶은데 뭔가 딱 와닿는게..음..

**Comment by kkh975** [comment]
논의는 슬렉에도 정리해서 올렸어여~

**Comment by mozodev** [comment]
welfare4u.com 으로 결정됨!
