### ISSUE TITLE
댓글 데이터 타임스탬프 방식으로

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/FdAS#21]
addDate / fixDate -> timestamp

**Comment by mozodev** [comment]
댓글만 아니라 전체 테스트 데이터에 날짜들 다 바꿨습니다.

**Comment by kkh975** [comment]
넵~ 혹시 DB쪽 데이터에도 반영된건가여? 
(나중에 돌아가면 다 지우긴 하겠지만...;;; 혹시나 해서 문의해봤어여~)
