### ISSUE TITLE
Facebook 앱 인증 설정 에러 수정하기

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/FdAS#26]
잘 되다가 왜 그런지 모르겠음.. 증상 파악 중

**Comment by kkh975** [comment]
Scope를 필요한걸 추가했어요!

**Comment by mozodev** [comment]
Review

If your app asks for more than than public_profile, email and user_friends it will require review by Facebook before your app can be used by people other than the app's developers.

The time to review your app is usually about 7 business days. Some extra-sensitive permissions, as noted below, can take up to 14 business days.

Learn more about our review process in our documentation on reviews.

```
"scope": ["email", "user_birthday", "user_location", "user_photos"]
```

현재 스코프가 저러니까 실제 서비스용 심사 받아야 해결되는군요... 
당장 추가할 코드에서 필요한게 아니라면 그냥 제가 ```"user_birthday", "user_location", "user_photos"```는 서버에서 삭제하겠습니다.

**Comment by kkh975** [comment]
넵~

**Comment by mozodev** [comment]
잘 되네요 이게 문제였음..
