### ISSUE TITLE
Angular URL에 비의존적으로

### ISSUE THREAD

**Issue by kkh975** [codeforseoul/FdAS#29]
경로가 일치되지 않으면 실행이 안되는 경우가 많음.
로컬 / 스테이징 서버 / 실서버를 나누어서 개발을 해야하는데 불편함이 많아 수정 필요

**Comment by thechunsik** [comment]
https://github.com/angular-ui/ui-router/wiki route 대신 state 으로 관리하는 도구에요, 추천!

**Comment by kkh975** [comment]
처음에 이걸로 했다가 다시 변경했어요...살짝 불안불안...
아마 PC 버젼 오픈때는 쓰긴 해야할 것 같은데 지금은 전역변수에 의존하는것만 없앨려구여~

**Comment by kkh975** [comment]
window.location.url 좀 정리 좀 했습니다. ㅋ
