### ISSUE TITLE
UX/UI 수정사항

### ISSUE THREAD

**Issue by Yeyeon** [codeforseoul/FdAS#30]
2015.01.23
- 메인 상단 “서울의발견” ->”알뜰서울의발견” 으로 수정
- 메인 우측상단 개인설정, 관심사 아이콘 라인아이콘으로 수정
- 페이스북, “…”눌렀을때 팝업창, 아이폰에서 오른쪽 밀림 현상 수정 (ㅜ.ㅜ)
- 스크롤시 부드럽게 이동 (가능한가요..?;)

**Comment by Yeyeon** [comment]
2015.01.26

- 상단 메뉴바랑 검색창이 고정되어야..!?

**Comment by kkh975** [comment]
- 스크롤시 부드럽게 이동 <- 요건 제가 생각하지 못한 영역이 있어, 살짝 수정이 더 들어가야 할 듯해요...
오늘 발표때는 이 부분은 제외할꼐요.. 나머지는 일딴 완료한듯!

**Comment by iz4blue** [comment]
[http://welfare4u.com/#/category] 에서 관심사 설정을 눌러도 예전 페이지로 이동 가능하는 것이 좋을 것 같아요.

**Comment by kkh975** [comment]
@iz4blue  등록하신 세가지 의견은 이슈 하나 추가해서 따로 등록할께여~
