### ISSUE TITLE
마일스톤 정리 필요

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/FdAS#35]
이슈를 작성하다가 마일스톤을 클릭해보니 

```
frontend
scraping
service beta
```

이렇게 3개 마일스톤이 보이는데 마감을 3달 이상 넘겼네요.
어쨌든 완성하기로 마음먹었으니까 좀 구체적으로 마일스톤 일정을 정리해보면 좋겠습니다.
한 번 고민해보시고 다음 핵나잇 때 세부적으로 좀 이야기해서 결정합시다!

**Comment by kkh975** [comment]
service beta 같은 경우는 제가 어제 추가하기 했어요~
개인적인 의견을 보태면, frontend 마일스톤 같은 경우는 초기 구축시 프런트 개발이라고 이해했습니다.
그래서 frontend는 close 하고 지금은 service beta 마일스톤으로 넘어가야 한다고 생각하고 있습니다.

**Comment by mozodev** [comment]
ㅇㅇ 그게 잘못됐다는게 아니라 좀 구체적으로 완성하려면 뭐뭐가 되야하고 그게 언제까지다 이런 계획을 세우자는거죠~ 
일단 스크레이핑, 일단 복지로만 한다고 할 때 마크업 분석하는게 시간이 걸릴꺼고 긁어와서 db에 넣는건 어렵지 않으나 타임아웃 있어서 1~2초 정도 쉬면서 긁어오면 1~2일 걸릴꺼고... 여기에 분류하는 것까지 하면 레코드가 몇 개니까 몇 명이 나눠서 입력한다고 하면 몇일 걸릴꺼고....

이것만 봐도 이렇게든요. 
뜬구름 잡는게 아니고 실제 뭘 어디까지 할지 정하고 누가 몇일동안해서 끝낸다.. 이런 계획 말이죠....
IMHO (In My Humble Opinion) 뭘 어디까지 할지라도 정하는데 진심으로 이걸 끝내려는 자의 자세이어야 한다고 생각해요....

**Comment by kkh975** [comment]
이모티콘 없이 제가 넘 강하게 썼나봐여 ㅋㅋㅋ 
별건 아니고, 어제 service beta 추가한거에 대한 개인적인 의견만 달은거예요~ ㅎ
